services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: airport-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: airport-backend
    command: ["uvicorn", "app.main:app", "--host", "${BACKEND_HOST}", "--port", "${BACKEND_PORT}", "--reload"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_INTERNAL_HOST}
      - POSTGRES_PORT=${POSTGRES_INTERNAL_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_ENV=${APP_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      # Bind-mount папки sql внутрь контейнера
      - ./backend/sql:/app/sql

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge